/** Icon names available in <Icon />. Kept in its own module so props can be typed. */
export type IconName =
	| 'overview'
	| 'users'
	| 'projects'
	| 'assign'
	| 'logs'
	| 'plugins'
	| 'search'
	| 'bell'
	| 'chevron-down'
	| 'menu'
	| 'close'
	| 'logout'
	| 'plus'
	| 'check'
	| 'copy'
	| 'edit'
	| 'trash'
	| 'refresh'
	| 'alert'
	| 'download'
	| 'filter'
	| 'activity';
